import { z } from "zod";

// Stored optionally on old storyboards; required by the current V3 director.
// These are production instructions, never additional visible copy.
export const productionBriefSchema = z.object({
  buyerTakeaway: z.string().min(10).max(250),
  narrativeLink: z.string().min(10).max(250),
  visualProof: z.string().min(15).max(400),
  layoutBlueprint: z.string().min(30).max(600),
  materialTreatment: z.string().min(15).max(350),
  interaction: z.string().min(10).max(300),
  copyArchitecture: z.string().min(10).max(300),
  differenceFromPrevious: z.string().min(15).max(350),
  supportingModules: z.array(z.object({
    purpose: z.string().min(5).max(200),
    visual: z.string().min(10).max(300),
    placement: z.string().min(10).max(250),
    factIds: z.array(z.string()).max(12),
    textBlockIndexes: z.array(z.number().int().min(0).max(5)).max(6),
  })).max(3),
});

const sourceGroundingGuide = `SOURCE RECONCILIATION: Inspect original product pixels independently BEFORE reading the suggested narrative. Descriptions and previous summaries may contain mistakes. A claim copied from description is source=user, never source=image just because an image ID exists. If text contradicts a directly visible physical feature, preserve the photographed feature and keep the disputed claim out of the campaign; ask only if that conflict is critical. A still photo of an extended part does not prove folding/retraction, removability or an operating sequence. Require explicit reliable evidence of the mechanism before planning a transformed state. Never invent a hinge or altered plug shape to satisfy a storyline. Reviewers must recheck source provenance and visible physical structure before typography/composition, even when the plan labels a claim verified.`;

export const productionPlanningGuide = `COMMERCIAL CONTENT STRATEGY:
${sourceGroundingGuide}
Default to information-rich commercial storytelling: plan strong evidence-backed selling messages, explanatory detail and useful buyer guidance. A mature set normally combines a clear headline-led opening with annotated proof, usage/context and a structured closing. Do not default to a mostly wordless photo catalog. An explicit user request for quiet imagery or pure photography overrides this default.
Never make "what the photo cannot confirm", "read the printed rating", "verify the unknown parameters" or an evidence-audit report the purpose of a sales image unless explicitly requested. Keep those limitations internal. Replace such slots with a supported purchase reason and a relevant demonstration, not another angle or appearance report.
Do not allocate an entire detail screen merely to reading a brand/rating printed on the shell. For a confirmed folding wall charger, easier packing may be a purchase reason, the folding mechanism its feature, and a packing scene or close demonstration its proof. The camera angle and hand-to-object scale are ways to show that reason, not themselves selling points. Distinguish the buyer's benefit from the shot used to demonstrate it.
Build a buyer journey around distinct evidence-backed or modestly inferred purchase reasons, recorded in sellingPoints and summarized in positioning. Each sales frame develops a reason; do not list superficial observations as separate benefits. HERO frames communicate value independently; DETAIL frames deepen it through relevant proof, use and guidance. Finish with the required known-parameter page. Do not invent gift contents or comparisons to fill slots.
Use photographic evidence and useful language together. A shortage of technical facts does not mean a shortage of design: garment drape on a moving wearer, a hand demonstrating a known lid, context showing scale, a macro of an observed finish, or an editorial product arrangement can communicate real value. Evidence from a printed label supports describing that label, not an independently tested performance claim. Do not plan "visible marking", "unknown parameters" or generic quality slogans as buyer benefits. Do not substitute seven identical product portraits for a sales narrative. Preserve explicit requests for pure photography or a particular text density.`;

export const productionDirectorGuide = `COMMERCIAL PRODUCTION BRIEF — complete production for EVERY frame:
${sourceGroundingGuide}
Write concise, execution-ready fields: one concrete sentence per production field, typically 15-35 words. Schema maximum lengths are ceilings, not targets. Avoid repeating the same rule across fields.
DEFAULT DIRECTION: rich commercial image-and-copy design. Give the opening a distinctive, prominent selling headline; build subsequent evidence/usage pages with clear annotation, explanation and layered type. Prefer statement, annotation or information when words help a buyer understand the product. Use 1-3 supporting modules where the facts warrant them, especially explanation and selection pages. Reserve pure photography for a deliberate emotional or contextual pause, not the automatic choice for every macro or scene. Richness means useful hierarchy, not more unverified claims or tiny text. Respect an explicit user request for sparse/pure-photographic work.
1. buyerTakeaway: the single useful impression/question this image resolves. narrativeLink: which purchase reason from the plan it develops. visualProof: the concrete thing the viewer will see that carries it, grounded in the assigned facts; this is not a laboratory claim.
2. layoutBlueprint: specify primary subject region, approximate frame coverage, secondary regions, text reserve, alignment and reading order. Give usable spatial relationships (e.g. close detail fills the right two thirds, two small evidence crops stacked in the left third). These are composition directions, not visible coordinates. Make one focal point dominant; never use equal-weight collage by default.
3. materialTreatment: specify how real surface roughness, fabric weave, ceramic glaze, translucent walls or brushed edges respond to this light. interaction: a specific plausible action/gesture or grounded still-life relationship. People, hands, hair, fabric motion and contextual props are available when appropriate; do not omit them merely to simplify rendering. Keep human anatomy, contact, weight, reflections and shadows credible. Props are context, not included accessories.
4. copyArchitecture: select a useful copy form (compact claim with evidence labels, local annotation, short explanation, small steps, verified facts, or deliberately wordless photograph) and explain the hierarchy. Write the actual words ONLY in textBlocks. Use a dominant claim plus 1-3 concise subordinate points when evidence supports them; a photo can have zero. Never impose a universal word quota. Empty copy is a design choice, not a fallback for every page. User-required wording and language take precedence.
COPY TRANSFORMATION: lead with the mapped buyer benefit, support it with the real feature, and show the relevant proof. For a confirmed folding plug, "折起就收好，出门少一份累赘" communicates packing value, with "折叠插脚" as a subordinate feature label. Rewording a shape observation as "圆角与折面，勾勒利落轮廓" still fails if it never explains buyer value. For teaware, connect a supported feature to preparing or enjoying tea; for apparel, connect the actual cut to a wearing/styling idea. Object names such as "盖钮" or "USB" are useful small labels, not enough as a whole page's proposition. Natural use and emotional context are allowed without manufacturing material, comfort, safety or performance claims. Do not print "可见/可确认/仅作外观信息" prefixes.
CUSTOMER COPY BOUNDARY: "手边的相对尺寸", "从上方看圆形盖面", "回看外观", "手持尺度参照", camera angles, observation instructions and page-role narration belong ONLY in internal task/camera/production fields. Never copy them into textBlocks or paint them as titles/captions, even if they are factually accurate. Write a natural product heading or precise feature label (for example a verified component name, "盖碗参数", or a supported short buyer benefit), or use a deliberate wordless scene. The product's real printed labels and literal user-required wording remain intact. A specifications page must present verified label/value information, not explain how the Agent looked at the product.
5. supportingModules: 0-3 subordinate detail crops, action insets, annotation groups, steps or verified facts. Each has purpose, actual visual, placement, existing factIds and zero-based textBlockIndexes pointing into this frame's textBlocks. Reuse the same SKU. Label a detail crop locally; use a leader only when its endpoint can unambiguously land on the named physical feature. Prefer a nearby label over a long line crossing another component. No invented technical diagrams, duplicated decorative mini-products or unsupported comparisons. Pure photography uses [] here.
6. differenceFromPrevious: specify changes in camera distance, occupied area, action, visual proof, module structure and reading path, not just a renamed composition or slightly rotated object. A macro frame makes a real detail fill the primary photograph and may crop away the rest of the product; a whole packshot plus a small inset is not macro photography. An environmental frame gives the setting/action enough area to explain the context rather than replacing the pedestal behind another giant packshot. First frame describes its thumbnail hierarchy. A quiet frame still needs authored light, staging and a useful task.
Keep a campaign world through palette, light direction, related surfaces, letterform family and a recognizable motif, while varying shot scale and information density. Share a visual language, not a cloned layout. Do not default every category to gray product-on-plinth renders. Do not force every detail screen to restart as a full-size poster cover.
Reference mechanics, not literal templates: apparel = full-body motion / fabric macro / useful fit detail / different wearing context; appliance = product identity / hand-held scale / real use / relevant surface or control detail; drinkware = lifestyle / verified construction / handling / selection; ceramics = lifting a lid / glaze macro / visible separate parts / pouring / quiet table setting. Use only actions/features supported for the actual product. Gift packaging, dimensions, performance outcomes and certifications require supplied evidence.
Maturity comes from specific art direction and useful information hierarchy, not mandatory decoration or maximal text. Inspect reference images for scale, light, interaction, text integration and module hierarchy, not just color.`;

export const productionReviewGuide = `COMMERCIAL EXECUTION REVIEW:
${sourceGroundingGuide}
Check whether the production brief's visualProof is actually legible, the product is physically grounded, material/light has controlled detail, the focal hierarchy matches layoutBlueprint, and planned supporting modules carry useful evidence instead of clutter. A correct SKU floating over an empty gradient is insufficient when an action, context or evidence module was planned. Do not pass an image solely because its words are spelled correctly.
Reject camera/analysis narration in visible copy, including "手边的相对尺寸", "从上方看圆形盖面" and "回看外观". Preserve category content jobs: the final parameter table, any real supplied size chart, and apparel on-body imagery cannot be replaced by an appearance recap or generic portrait. Check labels, values, units and table row relationships against productInformation.
For continuous DETAIL pages, compare the actual previous bottom and current top across the width. Actual saved neighbor pixels take precedence over planned HEX seam targets. A matching plan color does not pass when the actual neighboring edge differs; conversely do not fail a visually continuous join just because both images differ from a planned color. Judge natural color/luminance/texture flow, not a flat colored strip.
Compare actual neighboring frames: can the buyer learn something different, and do shot distance, subject coverage, action and reading path change? Inspect text at 375px, reduce oversized generic slogans, and preserve useful subcopy/labels. Do not remove useful information just to make everything photographic. A deliberately wordless scene can pass without titles. Every failed judgment must identify a visible defect and a local repair; no subjective paid retry for a merely different but successful composition. Do not demand unsupported claims, props sold as accessories, invented dimensions or hidden mechanisms.`;
